# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_app', '0010_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
